name: Linting & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.25']

    services:
      chromedp:
        image: docker.io/chromedp/headless-shell:latest
        ports:
          - 9222:9222

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Disable AppArmor unprivileged userns restriction
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

    - name: Set up tools
      env:
        PISCES_CHROMEDP_REMOTE_URL: "http://localhost:9222"
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run linting
      run: make check

    - name: Run tests
      run: make test
